import base64
from solders.transaction import Transaction,VersionedTransaction
import unittest

class Test_deserialize(unittest.TestCase):
    def test_deserialize_Transaction(self):
        transaction_data = "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAEFa4SRkltWRPaHxBCKcdBF7p0hj/7pfBx/ZG9GCe23AX0QblkmsoG9ssaUd+A6tiPwRUE6PRUKmWNU8A1Ah3nwvoGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAYdJHyr93kZVe3fwjUd0v6Zjt6u+AHztOU27bw8WzqCM8QwCOjPQZ2gnPDP+wTyiv1C+1USyRyPBs4cVSgILGgywFxPpUgFHwZQjb7Gz7Gh3LxSus7pxooYg9n89OEW+UesA2fWykrQhSsfQN7TW8GRQuWRgDfNzBSu16E8vjppnsyE/uov5yH+pHkeBlijDg+AL6n6Yx6A+A7oQac/D9vN3PZ8oPAtHI3dd9EsBUYDKIgl9uUF/AEG6ur7SyGPW8lyveOFQQ7/z9557wGQEuBQzoj1WdTQbCO2jqo8F4kTmp9bZR4aywgTs6Cn2/YYPbhmaMlfWSfb01Z+AoPrbUSzIwJb+SUU6kNnxy5vcrboboGUh01wgjY3x+gkt7fWL+s4BDmCv7bInF71jGS9UFFo/llozu4LSxwKess4eIIJk4qEYsbCZSQmYgHRlQG3e7FDy9Zt5df2nVps3jBiPZpB/vDeGJKhWrFINlM8ShBAU0xhbzPv2WxkKYMjM92RmrvyrVWZUSFJOhHmydJNeZaNSHZ5GTIjY5Ywi9i9Hetzqurer3R9iBUhHEXYAHrGTWixvB1k4JhsZF4V0umMfPs616LZnFNkZHAgiPOrd+k9EbmwM9DhNyY2aA4tZsJtKCgzCgMtr4xksUDg4Ac9EMBgPnj+GYyI6yAEGlxDb99UHqSpai08pWVKEJVCqk/1blbWs5qjrkgyTlC5DaQwg7HMDBkZv5SEXMv/srbpyw5vnvIzlu8X3EmssQ5s6QAAAAOIZZnHsr16RxLl9FE5hgdUcI8XtiHNw6M6flM1VyeJ6BhEBAAASBgABAhUWFwkFvCgCAAAAAAASGxUYFhcAAQMTBAIFBgcICQoLEwMFDAYHDQ4PEBEAvCgCAAAAAABhTgAAAAAAABIGAAEAFRYXAQYUAAkDnUcAAAAAAAAUAAUCwCcJAAEZjx9MOkUiY9QTss0X68vBoOWIc2TmJhoSqBeS6hZaPgAEAgcAAw=="
        
        transaction_byte = base64.b64decode(transaction_data)

        transaction = VersionedTransaction.from_bytes(transaction_byte)

        print(transaction)

if __name__ == '__main__':
    unittest.main()
